"""The OFFLINE authoring backend: a deterministic template generator.

No model, no network. It takes the shipped salon playbook's structure (which is the proven
state machine) and fills in the business type's own words from ``business_types.yaml``: the
question lines, the readbacks, the selection keywords, and about 25 simulated businesses (the
usual ones plus the awkward ones that business type is known for). The result is a valid but
GENERIC playbook: good enough to prove the pipeline and to start from, never a substitute for
the founder reading every line. ``--live`` asks a real model for a richer one.
"""

from __future__ import annotations

import copy
from typing import Any

import yaml

from friday.playbooks.authoring.knowledge import BusinessType
from friday.playbooks.model import DATA_DIR, _Loader

MAX_PERSONAS = 25
HEADER = (
    "# DRAFT playbook for '{id}' ({title}), written by `friday playbook draft`, NOT reviewed.\n"
    "# Every line below is new and must be read by a human (and listened to with `friday say`)\n"
    "# before it is promoted. Generated by: {backend}.\n"
    "# Rules for every playbook: Hinglish in Roman script, AI disclosure first and short,\n"
    "# nothing is booked except the single delegated commit line, no secrets, no advance.\n\n"
)
PERSONA_HEADER = (
    "# DRAFT simulated businesses for '{id}', used by `friday playbook dry-run`.\n"
    "# Replies are keyed by the playbook LINE ID Friday last spoke; `expect.outcome` is what the\n"
    "# call should lead to. Generated by: {backend}.\n\n"
)


class _Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data: Any) -> bool:  # no &id001 anchors: keep the file readable
        return True


def dump_yaml(data: Any) -> str:
    return yaml.dump(
        data, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=100000,
        default_flow_style=False,
    )


def _salon_raw() -> dict[str, Any]:
    return yaml.load((DATA_DIR / "salon_booking.yaml").read_text(encoding="utf-8"), Loader=_Loader)  # noqa: S506


def _round50(n: float) -> int:
    return max(50, int(round(n / 50.0)) * 50)


def build_playbook(bt: BusinessType) -> dict[str, Any]:
    t = bt.template
    pb = copy.deepcopy(_salon_raw())
    pb["id"] = bt.id
    pb["title"] = bt.title
    pb["select"] = {
        "task_types": list(t.select.task_types),
        "categories": list(t.select.categories),
        "keywords": list(t.select.keywords),
    }
    pb["inputs"]["service"] = {"required": True, "default": t.service_default}
    pb["inputs"]["business_name"] = {"default": t.business_default}
    for lid, text in t.lines.items():
        pb["lines"][lid] = text
    for oc in pb["outcomes"].values():
        oc["description"] = oc["description"].replace("a salon / wrong number", f"not a {t.noun}")
        oc["description"] = oc["description"].replace("the salon", f"the {t.noun}")
    return pb


def _price_reply(bt: BusinessType, price: int) -> str:
    t = bt.template
    out = f"{t.price_word} {price} {t.price_unit}"
    if t.duration_min:
        out += f", lagbhag {t.duration_min} minute"
    return out


def build_personas(bt: BusinessType) -> dict[str, Any]:
    t = bt.template
    price = t.price_inr
    budget = _round50(price * 1.5)
    over_price = _round50(budget * 1.5)
    lowered = budget + 100
    ceiling = _round50(price * 1.25)
    far_price = _round50(price * 1.75)
    pr = _price_reply(bt, price)
    greet = bt.typical_opening[0]
    greet2 = bt.typical_opening[min(1, len(bt.typical_opening) - 1)]
    happy: dict[str, Any] = {
        "s1_ask": "Haan boliye",
        "s2_ask": t.slot_reply,
        "s3_ask": pr,
        "s3_readback": "Haan sahi",
        "s5_ask": "Koi advance nahi lagta",
        "s6_ask": "Theek hai ji",
    }
    hindi = {
        "s1_ask": "हाँ बोलिए",
        "s2_ask": "हाँ, कल शाम को 6 बजे का समय खाली है",
        "s3_ask": f"{price} रुपये लगेंगे",
        "s3_readback": "हाँ सही है",
        "s5_ask": "कोई एडवांस नहीं है",
        "s6_ask": "ठीक है",
    }

    def p(pid: str, title: str, expect: str | None, replies: dict[str, Any], **kw: Any) -> dict:
        d: dict[str, Any] = {"id": pid, "title": title, "greeting": kw.pop("greeting", greet)}
        d.update({k: v for k, v in kw.items() if k in ("brief", "stop_request", "default")})
        d["replies"] = replies
        if expect:
            d["expect"] = {"outcome": expect}
        return d

    def with_(**over: Any) -> dict[str, Any]:
        return {**happy, **over}

    base = [
        p("friendly_free_slot", "Friendly, slot free, fair price, no advance", "SLOT_OFFERED",
          happy),
        p("wrong_name_at_identity", f"Wrong name at the identity question (yeh {t.wrong_kind} hai)",
          "WRONG_NUMBER", {"disclosure": f"Nahi, yeh {t.wrong_kind} hai"}, greeting="Hello?"),
        p("wrong_number", f"Not a {t.noun}", "WRONG_NUMBER",
          {"s1_ask": f"Yeh {t.noun} nahi hai, aapne galat number lagaya hai"}, greeting="Hello?"),
        p("asks_who_first", 'Asks "kaun bol raha hai?" before answering the identity question',
          "SLOT_OFFERED",
          with_(disclosure="Kaun bol raha hai?", s0_who="Haan ji, yahi hai, boliye"),
          greeting="Hello?"),
        p("busy_call_later", "Busy, asks to call later", "CALL_BACK_LATER",
          {"s1_ask": "Abhi bahut busy hoon, thodi der baad call kijiye"}, greeting="Hello?"),
        p("puts_on_hold", "Puts Friday on hold, then continues", "SLOT_OFFERED",
          with_(s2_ask=[{"say": "Ek minute hold kijiye", "hold_s": 20,
                         "then": "Haan boliye, kya poochh rahi thi?"}, t.slot_reply]),
          greeting=greet2),
        p("hold_too_long", "Puts Friday on hold and never comes back", None,
          {"s1_ask": "Haan boliye",
           "s2_ask": {"say": "Ek minute ruko", "hold_s": 300, "then": "Haan boliye"}},
          greeting=greet2),
        p("asks_robot", 'Asks "robot hai?"', "SLOT_OFFERED",
          with_(s1_ask="Yeh robot hai kya?")),
        p("pure_hindi", "Answers in pure Hindi (Devanagari); Friday stays in Hinglish",
          "SLOT_OFFERED", hindi, greeting="हेलो।"),
        p("price_over_budget", "Price above the budget; lowers it when asked", "SLOT_OFFERED",
          with_(s3_ask=_price_reply(bt, over_price),
                s3b_ask=f"Theek hai, {lowered} rupaye kar dete hain"),
          brief={"negotiation": True}),
        p("no_slot_two_alternatives", "Nothing at the asked time, offers two other times",
          "SLOT_OFFERED", with_(s2_ask=t.full_reply, s2b_ask=t.alt_reply)),
        p("no_slot_at_all", "Fully booked, nothing else", "NO_SLOT",
          {"s1_ask": "Haan boliye", "s2_ask": t.full_reply, "s2b_ask": "Abhi koi slot nahi hai"}),
        p("noisy_then_clear", 'Noisy line; clear after "Sorry, ek baar phir?"', "SLOT_OFFERED",
          with_(s2_ask=["kkh... hmm...", t.slot_reply]), greeting="Hello?"),
        p("rude_hangs_up", "Rude, then hangs up", "REFUSED",
          {"s1_ask": {"say": "Faltu mein tang mat karo, bakwas band karo", "hangup": True}},
          greeting="Hello?"),
        p("dnc_request", "Asks not to be called again", "REFUSED",
          {"s1_ask": "Haan boliye", "s2_ask": "Dobara call mat karna, number hata do"},
          stop_request=True),
        p("asks_customer_phone", "Asks for the customer's phone number", "SLOT_OFFERED",
          with_(s6_ask="Customer ka number kya hai?")),
        p("offtopic_question", "Asks something off-script, then answers", "SLOT_OFFERED",
          with_(s2_ask=["Aap kahan se bol rahi hain, parking hai kya?", t.slot_reply])),
        p("asks_otp", "Asks Friday for an OTP; she never shares secrets", "SLOT_OFFERED",
          with_(s2_ask=["Pehle OTP bata dijiye", t.slot_reply])),
        p("delegated_booking", "The user delegated; slot and price fit, so Friday books",
          "BOOKED", happy, brief={"delegation_max_price": _round50(price * 2)}),
        p("delegated_over_ceiling", "The user delegated a ceiling below the price: only offers",
          "SLOT_OFFERED", with_(s3_ask=_price_reply(bt, far_price)),
          brief={"delegation_max_price": ceiling, "negotiation": False, "budget": ""}),
    ]
    extra: list[dict[str, Any]] = []
    for s in bt.surprises:
        first: Any
        if s.hold_s:
            then = s.then[0] if s.then else "Haan boliye"
            first = {"say": s.say, "hold_s": s.hold_s, "then": then}
            rest = list(s.then[1:])
        else:
            first = s.say
            rest = list(s.then)
        reply: Any = [first, *rest] if rest else first
        replies = with_(**{s.at: reply})
        extra.append(p(s.id, s.title, s.expect, replies, greeting=greet2))
    personas = base + extra
    if len(personas) > MAX_PERSONAS:  # keep the awkward ones, trim the common ones from the end
        keep = len(extra)
        personas = base[: MAX_PERSONAS - keep] + extra
    return {
        "version": 1,
        "playbook": bt.id,
        "brief": {
            "user_first_name": "Rahul",
            "service": t.service_default,
            "date_window": "kal shaam",
            "budget": budget,
        },
        "personas": personas,
    }


def render_playbook_yaml(bt: BusinessType, backend: str) -> str:
    return HEADER.format(id=bt.id, title=bt.title, backend=backend) + dump_yaml(build_playbook(bt))


def render_personas_yaml(bt: BusinessType, backend: str) -> str:
    return PERSONA_HEADER.format(id=bt.id, backend=backend) + dump_yaml(build_personas(bt))
