# ruff: noqa
"""baseline schema (S-5)

Revision ID: 805f8a55f2d1
Revises:
Create Date: 2026-10-08 12:22:03.879090
"""

import sqlalchemy as sa
from alembic import op

import friday.db.base

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("actor", sa.String(length=10), nullable=False),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("subject_id", sa.String(length=32), nullable=True),
        sa.Column("detail", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index("ix_audit_user_at", ["user_id", "at"], unique=False)

    op.create_table(
        "dnc_registry",
        sa.Column("phone_hmac", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.Text(), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("number_phone", sa.String(length=20), nullable=True),
        sa.Column("at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dnc_registry")),
        sa.UniqueConstraint("phone_hmac", name=op.f("uq_dnc_registry_phone_hmac")),
    )
    op.create_table(
        "friday_numbers",
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=True),
        sa.Column("circle", sa.String(length=8), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("warmup_day", sa.Integer(), nullable=False),
        sa.Column("limits", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("health", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("cooldowns", sa.Integer(), nullable=False),
        sa.Column("cooling_until", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("retired_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("forward_until", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("verified_caller_name", sa.String(length=80), nullable=True),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_friday_numbers")),
        sa.UniqueConstraint("phone", name=op.f("uq_friday_numbers_phone")),
    )
    with op.batch_alter_table("friday_numbers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_friday_numbers_circle"), ["circle"], unique=False)
        batch_op.create_index(batch_op.f("ix_friday_numbers_status"), ["status"], unique=False)

    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("expires_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_idempotency_keys")),
    )
    with op.batch_alter_table("idempotency_keys", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_idempotency_keys_expires_at"), ["expires_at"], unique=False
        )

    op.create_table(
        "jobs",
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("due_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=True),
        sa.Column("partition_key", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("claimed_by", sa.String(length=80), nullable=True),
        sa.Column("lease_until", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=300), nullable=True),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_claim", ["status", "priority", "due_at"], unique=False)
        batch_op.create_index(
            "uq_jobs_live_dedupe",
            ["dedupe_key"],
            unique=True,
            postgresql_where=sa.text("status IN ('queued','claimed')"),
            sqlite_where=sa.text("status IN ('queued','claimed')"),
        )

    op.create_table(
        "number_assignments",
        sa.Column("business_phone_hmac", sa.String(length=64), nullable=False),
        sa.Column("business_phone", sa.Text(), nullable=False),
        sa.Column("number_phone", sa.String(length=20), nullable=False),
        sa.Column("assigned_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("previous_number", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("business_phone_hmac", name=op.f("pk_number_assignments")),
    )
    with op.batch_alter_table("number_assignments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_number_assignments_number_phone"), ["number_phone"], unique=False
        )

    op.create_table(
        "number_outcomes",
        sa.Column("number_phone", sa.String(length=20), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("business_phone_hmac", sa.String(length=64), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_number_outcomes")),
    )
    with op.batch_alter_table("number_outcomes", schema=None) as batch_op:
        batch_op.create_index("ix_number_outcomes_number_at", ["number_phone", "at"], unique=False)

    op.create_table(
        "pending_deletions",
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=200), nullable=True),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_deletions")),
    )
    op.create_table(
        "suppressions",
        sa.Column("phone_hmac", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=True),
        sa.Column("at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppressions")),
        sa.UniqueConstraint("phone_hmac", "scope", name=op.f("uq_suppressions_phone_hmac")),
    )
    with op.batch_alter_table("suppressions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_suppressions_phone_hmac"), ["phone_hmac"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("phone", sa.Text(), nullable=False),
        sa.Column("phone_hmac", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("onboarding_step", sa.String(length=20), nullable=False),
        sa.Column("pin_hash", sa.String(length=255), nullable=True),
        sa.Column("pin_failed_attempts", sa.Integer(), nullable=False),
        sa.Column("invited_by_user_id", sa.String(length=32), nullable=True),
        sa.Column("invites_remaining", sa.Integer(), nullable=False),
        sa.Column("rate_limited", sa.Boolean(), nullable=False),
        sa.Column("last_inbound_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("phone_hmac", name=op.f("uq_users_phone_hmac")),
    )
    op.create_table(
        "account_identifiers",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("company", sa.String(length=120), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("value_encrypted", sa.Text(), nullable=False),
        sa.Column("last4", sa.String(length=4), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_account_identifiers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_identifiers")),
    )
    with op.batch_alter_table("account_identifiers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_account_identifiers_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "autonomy_settings",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_autonomy_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "category", name=op.f("pk_autonomy_settings")),
    )
    op.create_table(
        "businesses",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("whatsapp_phone", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=60), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("hours", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=True),
        sa.Column(
            "best_call_times", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False
        ),
        sa.Column("is_customer_care", sa.Boolean(), nullable=False),
        sa.Column("ivr_notes", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("verification", sa.String(length=12), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("language_hint", sa.String(length=12), nullable=True),
        sa.Column("directory_provider", sa.String(length=30), nullable=True),
        sa.Column("directory_place_id", sa.String(length=255), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=32), nullable=True),
        sa.Column("last_called_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_businesses_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_businesses")),
    )
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_businesses_directory_place_id"), ["directory_place_id"], unique=False
        )
        batch_op.create_index("ix_businesses_phone", ["phone"], unique=False)

    op.create_table(
        "cost_entries",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("task_id", sa.String(length=32), nullable=True),
        sa.Column("call_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("amount_inr", sa.Float(), nullable=False),
        sa.Column("at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_cost_entries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_entries")),
    )
    with op.batch_alter_table("cost_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cost_entries_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_cost_user_at", ["user_id", "at"], unique=False)

    op.create_table(
        "invites",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=32), nullable=True),
        sa.Column("redeemed_by_user_id", sa.String(length=32), nullable=True),
        sa.Column("redeemed_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("expires_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_invites_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["redeemed_by_user_id"],
            ["users.id"],
            name=op.f("fk_invites_redeemed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_invites")),
    )
    with op.batch_alter_table("invites", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invites_created_by_user_id"), ["created_by_user_id"], unique=False
        )

    op.create_table(
        "people",
        sa.Column("owner_user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("relation", sa.String(length=40), nullable=True),
        sa.Column("aliases", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("phone_hmac", sa.String(length=64), nullable=True),
        sa.Column("language", sa.String(length=12), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("contact_consent", sa.String(length=16), nullable=False),
        sa.Column("consent_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("checkin_consent", sa.String(length=16), nullable=False),
        sa.Column("linked_user_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["linked_user_id"],
            ["users.id"],
            name=op.f("fk_people_linked_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_people_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
    )
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_people_owner_user_id"), ["owner_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_people_phone_hmac"), ["phone_hmac"], unique=False)

    op.create_table(
        "pin_locks",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("strikes", sa.Integer(), nullable=False),
        sa.Column("locked_until", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("support_required", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=True),
        sa.Column("updated_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_pin_locks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_pin_locks")),
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("language", sa.String(length=12), nullable=False),
        sa.Column("tone", sa.String(length=12), nullable=False),
        sa.Column("morning_briefing", sa.Boolean(), nullable=False),
        sa.Column("briefing_hour_ist", sa.Integer(), nullable=False),
        sa.Column("preferred_channel", sa.String(length=12), nullable=False),
        sa.Column("updated_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_profiles")),
    )
    op.create_table(
        "consents",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("person_id", sa.String(length=32), nullable=True),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("evidence_text", sa.Text(), nullable=True),
        sa.Column("phone_hmac", sa.String(length=64), nullable=True),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("recorded_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_consents_person_id_people"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_consents_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
    )
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_consents_phone_hmac"), ["phone_hmac"], unique=False)
        batch_op.create_index(batch_op.f("ix_consents_user_id"), ["user_id"], unique=False)

    op.create_table(
        "facts",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("due_on", sa.Date(), nullable=True),
        sa.Column("recurrence", sa.String(length=10), nullable=False),
        sa.Column("business_id", sa.String(length=32), nullable=True),
        sa.Column("person_id", sa.String(length=32), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_message_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_facts_business_id_businesses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name=op.f("fk_facts_person_id_people"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_facts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facts")),
    )
    with op.batch_alter_table("facts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_facts_due_on"), ["due_on"], unique=False)
        batch_op.create_index(batch_op.f("ix_facts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "messages",
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("person_id", sa.String(length=32), nullable=True),
        sa.Column("business_id", sa.String(length=32), nullable=True),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("channel", sa.String(length=12), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("phone", sa.Text(), nullable=False),
        sa.Column("phone_hmac", sa.String(length=64), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("buttons", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("button_id", sa.String(length=256), nullable=True),
        sa.Column("template", sa.Text(), nullable=True),
        sa.Column("media_url", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("provider_message_id", sa.String(length=128), nullable=True),
        sa.Column("task_id", sa.String(length=32), nullable=True),
        sa.Column("nudge_id", sa.String(length=32), nullable=True),
        sa.Column("question_id", sa.String(length=32), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_messages_business_id_businesses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_messages_person_id_people"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_messages_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_phone_dir_at", ["phone_hmac", "direction", "at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_messages_phone_hmac"), ["phone_hmac"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_messages_provider_message_id"), ["provider_message_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_messages_task_id"), ["task_id"], unique=False)
        batch_op.create_index("ix_messages_user_at", ["user_id", "at"], unique=False)

    op.create_table(
        "places",
        sa.Column("owner_user_id", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("aliases", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("address_text", sa.Text(), nullable=True),
        sa.Column("formatted_address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("lat", sa.Text(), nullable=True),
        sa.Column("lng", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("person_id", sa.String(length=32), nullable=True),
        sa.Column("ephemeral", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_places_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_places_person_id_people"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_places")),
    )
    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_places_owner_user_id"), ["owner_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_places_person_id"), ["person_id"], unique=False)

    op.create_table(
        "vendor_interactions",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("business_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("task_id", sa.String(length=32), nullable=True),
        sa.Column("call_id", sa.String(length=32), nullable=True),
        sa.Column("amount_inr", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=200), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_vendor_interactions_business_id_businesses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_vendor_interactions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_interactions")),
    )
    with op.batch_alter_table("vendor_interactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vendor_interactions_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index("ix_vendor_user_business", ["user_id", "business_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("requester_user_id", sa.String(length=32), nullable=False),
        sa.Column("beneficiary_person_id", sa.String(length=32), nullable=True),
        sa.Column("place_id", sa.String(length=32), nullable=True),
        sa.Column("parent_task_id", sa.String(length=32), nullable=True),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("spec", sa.Text(), nullable=False),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("recurrence", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=True),
        sa.Column("next_run_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("last_outcome", sa.String(length=20), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("candidate", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=True),
        sa.Column("shortlist", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("approved_terms", sa.Text(), nullable=True),
        sa.Column("delegation", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=True),
        sa.Column("cost_inr_est", sa.Float(), nullable=False),
        sa.Column("source_message_id", sa.String(length=32), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["beneficiary_person_id"],
            ["people.id"],
            name=op.f("fk_tasks_beneficiary_person_id_people"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["tasks.id"],
            name=op.f("fk_tasks_parent_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["place_id"], ["places.id"], name=op.f("fk_tasks_place_id_places"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["requester_user_id"],
            ["users.id"],
            name=op.f("fk_tasks_requester_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_next_run_at"), ["next_run_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tasks_parent_task_id"), ["parent_task_id"], unique=False
        )
        batch_op.create_index(
            "ix_tasks_requester_status", ["requester_user_id", "status"], unique=False
        )
        batch_op.create_index("ix_tasks_status_next", ["status", "next_attempt_at"], unique=False)

    op.create_table(
        "call_memory",
        sa.Column("call_id", sa.String(length=32), nullable=True),
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("business_id", sa.String(length=32), nullable=True),
        sa.Column("business_phone", sa.Text(), nullable=False),
        sa.Column("business_phone_hmac", sa.String(length=64), nullable=False),
        sa.Column("friday_number", sa.String(length=20), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("outcome", sa.String(length=24), nullable=True),
        sa.Column("at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_call_memory_business_id_businesses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_call_memory_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_call_memory_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_memory")),
        sa.UniqueConstraint("call_id", name=op.f("uq_call_memory_call_id")),
    )
    with op.batch_alter_table("call_memory", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_call_memory_business_phone_hmac"), ["business_phone_hmac"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_call_memory_friday_number"), ["friday_number"], unique=False
        )
        batch_op.create_index(
            "ix_call_memory_phone_at", ["business_phone_hmac", "at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_call_memory_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_call_memory_user_id"), ["user_id"], unique=False)

    op.create_table(
        "call_questions",
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.Column("call_id", sa.String(length=32), nullable=True),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("options", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("timeout_s", sa.Integer(), nullable=False),
        sa.Column("asked_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("answer_option_index", sa.Integer(), nullable=True),
        sa.Column("answer_approves", sa.Boolean(), nullable=True),
        sa.Column("answered_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_call_questions_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_questions")),
    )
    with op.batch_alter_table("call_questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_call_questions_task_id"), ["task_id"], unique=False)

    op.create_table(
        "calls",
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_call_id", sa.String(length=128), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("to_phone", sa.Text(), nullable=False),
        sa.Column("business_id", sa.String(length=32), nullable=True),
        sa.Column("dial_status", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("collected", sa.Text(), nullable=False),
        sa.Column(
            "languages_heard", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False
        ),
        sa.Column("care", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=True),
        sa.Column("hold_seconds", sa.Integer(), nullable=False),
        sa.Column("cost_inr_est", sa.Float(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("recording_url", sa.Text(), nullable=True),
        sa.Column("started_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("answered_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("ended_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_calls_business_id_businesses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_calls_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calls")),
    )
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calls_provider_call_id"), ["provider_call_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_calls_task_id"), ["task_id"], unique=False)

    op.create_table(
        "hotel_bookings",
        sa.Column("task_id", sa.String(length=32), nullable=True),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("guest_person_id", sa.String(length=32), nullable=True),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("property", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("business_id", sa.String(length=32), nullable=True),
        sa.Column("room_type", sa.String(length=120), nullable=True),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("guests", sa.Integer(), nullable=False),
        sa.Column("total_inr", sa.Integer(), nullable=True),
        sa.Column("confirmation_ref", sa.String(length=80), nullable=True),
        sa.Column("booking_link", sa.Text(), nullable=True),
        sa.Column("hold_until", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("guest_name", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_hotel_bookings_business_id_businesses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["guest_person_id"],
            ["people.id"],
            name=op.f("fk_hotel_bookings_guest_person_id_people"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_hotel_bookings_task_id_tasks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_hotel_bookings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotel_bookings")),
    )
    with op.batch_alter_table("hotel_bookings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_hotel_bookings_check_in"), ["check_in"], unique=False)
        batch_op.create_index(batch_op.f("ix_hotel_bookings_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_hotel_bookings_user_id"), ["user_id"], unique=False)

    op.create_table(
        "inbound_contacts",
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("channel", sa.String(length=12), nullable=False),
        sa.Column("from_phone", sa.Text(), nullable=False),
        sa.Column("from_phone_hmac", sa.String(length=64), nullable=False),
        sa.Column("friday_number", sa.String(length=20), nullable=True),
        sa.Column("provider_ref", sa.String(length=128), nullable=True),
        sa.Column("call_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("business_id", sa.String(length=32), nullable=True),
        sa.Column("task_id", sa.String(length=32), nullable=True),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column(
            "candidate_task_ids", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("handled", sa.Boolean(), nullable=False),
        sa.Column("at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_inbound_contacts_business_id_businesses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_inbound_contacts_task_id_tasks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_inbound_contacts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbound_contacts")),
    )
    with op.batch_alter_table("inbound_contacts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_inbound_contacts_phone_at", ["from_phone_hmac", "at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_inbound_contacts_task_id"), ["task_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inbound_contacts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "nudges",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("urgency", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("buttons", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("proposed_task", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=True),
        sa.Column("task_id", sa.String(length=32), nullable=True),
        sa.Column("fact_id", sa.String(length=32), nullable=True),
        sa.Column("person_id", sa.String(length=32), nullable=True),
        sa.Column("recipient_person_id", sa.String(length=32), nullable=True),
        sa.Column("scheduled_for", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("sent_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("responded_at", friday.db.base.UTCDateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["fact_id"], ["facts.id"], name=op.f("fk_nudges_fact_id_facts"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["people.id"],
            name=op.f("fk_nudges_person_id_people"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_person_id"],
            ["people.id"],
            name=op.f("fk_nudges_recipient_person_id_people"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_nudges_task_id_tasks"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_nudges_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nudges")),
        sa.UniqueConstraint("user_id", "dedupe_key", name=op.f("uq_nudges_user_id")),
    )
    with op.batch_alter_table("nudges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_nudges_scheduled_for"), ["scheduled_for"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_nudges_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_nudges_user_sent", ["user_id", "sent_at"], unique=False)

    op.create_table(
        "call_turns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("call_id", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.String(length=8), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=12), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_call_turns_call_id_calls"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_turns")),
        sa.UniqueConstraint("call_id", "seq", name=op.f("uq_call_turns_call_id")),
    )
    with op.batch_alter_table("call_turns", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_call_turns_call_id"), ["call_id"], unique=False)

    op.create_table(
        "nudge_feedback",
        sa.Column("nudge_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=12), nullable=False),
        sa.Column("at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["nudge_id"],
            ["nudges.id"],
            name=op.f("fk_nudge_feedback_nudge_id_nudges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_nudge_feedback_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nudge_feedback")),
    )
    with op.batch_alter_table("nudge_feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nudge_feedback_nudge_id"), ["nudge_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_nudge_feedback_user_id"), ["user_id"], unique=False)

    op.create_table(
        "quotes",
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.Column("call_id", sa.String(length=32), nullable=True),
        sa.Column("business_id", sa.String(length=32), nullable=True),
        sa.Column("business_name", sa.String(length=200), nullable=False),
        sa.Column("amount_inr", sa.Integer(), nullable=True),
        sa.Column("original_amount_inr", sa.Integer(), nullable=True),
        sa.Column("price_text", sa.Text(), nullable=False),
        sa.Column("inclusions", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("exclusions", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False),
        sa.Column("validity", sa.String(length=200), nullable=True),
        sa.Column(
            "available_slots", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("within_budget", sa.Boolean(), nullable=True),
        sa.Column("created_at", friday.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_id"],
            ["businesses.id"],
            name=op.f("fk_quotes_business_id_businesses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["call_id"], ["calls.id"], name=op.f("fk_quotes_call_id_calls"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_quotes_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotes")),
    )
    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_quotes_task_id"), ["task_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quotes_task_id"))

    op.drop_table("quotes")
    with op.batch_alter_table("nudge_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nudge_feedback_user_id"))
        batch_op.drop_index(batch_op.f("ix_nudge_feedback_nudge_id"))

    op.drop_table("nudge_feedback")
    with op.batch_alter_table("call_turns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_call_turns_call_id"))

    op.drop_table("call_turns")
    with op.batch_alter_table("nudges", schema=None) as batch_op:
        batch_op.drop_index("ix_nudges_user_sent")
        batch_op.drop_index(batch_op.f("ix_nudges_user_id"))
        batch_op.drop_index(batch_op.f("ix_nudges_scheduled_for"))

    op.drop_table("nudges")
    with op.batch_alter_table("inbound_contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inbound_contacts_user_id"))
        batch_op.drop_index(batch_op.f("ix_inbound_contacts_task_id"))
        batch_op.drop_index("ix_inbound_contacts_phone_at")

    op.drop_table("inbound_contacts")
    with op.batch_alter_table("hotel_bookings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hotel_bookings_user_id"))
        batch_op.drop_index(batch_op.f("ix_hotel_bookings_task_id"))
        batch_op.drop_index(batch_op.f("ix_hotel_bookings_check_in"))

    op.drop_table("hotel_bookings")
    with op.batch_alter_table("calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calls_task_id"))
        batch_op.drop_index(batch_op.f("ix_calls_provider_call_id"))

    op.drop_table("calls")
    with op.batch_alter_table("call_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_call_questions_task_id"))

    op.drop_table("call_questions")
    with op.batch_alter_table("call_memory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_call_memory_user_id"))
        batch_op.drop_index(batch_op.f("ix_call_memory_task_id"))
        batch_op.drop_index("ix_call_memory_phone_at")
        batch_op.drop_index(batch_op.f("ix_call_memory_friday_number"))
        batch_op.drop_index(batch_op.f("ix_call_memory_business_phone_hmac"))

    op.drop_table("call_memory")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_status_next")
        batch_op.drop_index("ix_tasks_requester_status")
        batch_op.drop_index(batch_op.f("ix_tasks_parent_task_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_next_run_at"))

    op.drop_table("tasks")
    with op.batch_alter_table("vendor_interactions", schema=None) as batch_op:
        batch_op.drop_index("ix_vendor_user_business")
        batch_op.drop_index(batch_op.f("ix_vendor_interactions_user_id"))

    op.drop_table("vendor_interactions")
    with op.batch_alter_table("places", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_places_person_id"))
        batch_op.drop_index(batch_op.f("ix_places_owner_user_id"))

    op.drop_table("places")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_user_at")
        batch_op.drop_index(batch_op.f("ix_messages_task_id"))
        batch_op.drop_index(batch_op.f("ix_messages_provider_message_id"))
        batch_op.drop_index(batch_op.f("ix_messages_phone_hmac"))
        batch_op.drop_index("ix_messages_phone_dir_at")

    op.drop_table("messages")
    with op.batch_alter_table("facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_facts_user_id"))
        batch_op.drop_index(batch_op.f("ix_facts_due_on"))

    op.drop_table("facts")
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consents_user_id"))
        batch_op.drop_index(batch_op.f("ix_consents_phone_hmac"))

    op.drop_table("consents")
    op.drop_table("profiles")
    op.drop_table("pin_locks")
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_people_phone_hmac"))
        batch_op.drop_index(batch_op.f("ix_people_owner_user_id"))

    op.drop_table("people")
    with op.batch_alter_table("invites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invites_created_by_user_id"))

    op.drop_table("invites")
    with op.batch_alter_table("cost_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_cost_user_at")
        batch_op.drop_index(batch_op.f("ix_cost_entries_user_id"))

    op.drop_table("cost_entries")
    with op.batch_alter_table("businesses", schema=None) as batch_op:
        batch_op.drop_index("ix_businesses_phone")
        batch_op.drop_index(batch_op.f("ix_businesses_directory_place_id"))

    op.drop_table("businesses")
    op.drop_table("autonomy_settings")
    with op.batch_alter_table("account_identifiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_identifiers_user_id"))

    op.drop_table("account_identifiers")
    op.drop_table("users")
    with op.batch_alter_table("suppressions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suppressions_phone_hmac"))

    op.drop_table("suppressions")
    op.drop_table("pending_deletions")
    with op.batch_alter_table("number_outcomes", schema=None) as batch_op:
        batch_op.drop_index("ix_number_outcomes_number_at")

    op.drop_table("number_outcomes")
    with op.batch_alter_table("number_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_number_assignments_number_phone"))

    op.drop_table("number_assignments")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_jobs_live_dedupe",
            postgresql_where=sa.text("status IN ('queued','claimed')"),
            sqlite_where=sa.text("status IN ('queued','claimed')"),
        )
        batch_op.drop_index("ix_jobs_claim")

    op.drop_table("jobs")
    with op.batch_alter_table("idempotency_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_idempotency_keys_expires_at"))

    op.drop_table("idempotency_keys")
    with op.batch_alter_table("friday_numbers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_friday_numbers_status"))
        batch_op.drop_index(batch_op.f("ix_friday_numbers_circle"))

    op.drop_table("friday_numbers")
    op.drop_table("dnc_registry")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_user_at")

    op.drop_table("audit_log")
    # ### end Alembic commands ###
